services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.client
      args:
        - API_HOST=backend
        - API_PORT=5000
    image: somerandomname.client        
    container_name: somerandomname-client-container
    env_file:       
      - path: .env  
        required: false        
    ports:
      - ${APP_PORT:-80}:80 # APP_PORT can be set in .env file
    networks:
      - internal

  backend:
    build: 
      context: .
      dockerfile: Dockerfile.api      
      args:
        - PORT=5000
        - DB_CONNECTION_STRING=${DB_CONNECTION_STRING} # DB_CONNECTION_STRING can be set in .env file
    image: somerandomname.api
    container_name: somerandomname-api-container
    
    networks:
      - internal

  db:
    build:
      context: .
      dockerfile: Dockerfile.psql        
    image: somerandomname.db
    container_name: somerandomname-db-container  
    environment:
      POSTGRES_USER: postgres    
      POSTGRES_PASSWORD: postgres  
      PGDATA: /var/lib/postgresql/data/pgdata    
    
    networks:
      - internal

networks:
  internal: